### ISSUE TITLE
[New Package]: Ximalaya.Ximalaya

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#251]
### List the PackageIdentifier of the package to be added to automation

Ximalaya.Ximalaya

### Details about the application

```PowerShell
$result = Invoke-RestMethod 'https://pc.ximalaya.com/ximalaya-pc-updater/api/v1/update/full/latest.yml' -Headers @{
platform = 'win32'
buildversion = '0'
version = '0.0.0'
uid = ''
} | ConvertFrom-Yaml
```

Sometimes this source may return version only, which is the same as the one in the request header:
```Yaml
version: 0.0.0
```
And this is what it should return:
```Yaml
version: 2.4.0
files:
  - url: Ximalaya_2.4.0_1642057344.exe
    sha512: A61sOh6a2MrflFOAts1HrHP0NLmFXSNW43C8EchVik+UwQHFczl9I05GSZjRa+sGX3dH0xhdxO5EKywt1pPZTg==
    size: 76804032
path: Ximalaya_2.4.0_1642057344.exe
sha512: A61sOh6a2MrflFOAts1HrHP0NLmFXSNW43C8EchVik+UwQHFczl9I05GSZjRa+sGX3dH0xhdxO5EKywt1pPZTg==
releaseNotes: |-
  - 签到可领小雅皮肤啦
  - 声音评论无法查看问题修复
  - 字幕功能新增更多样式
  - 其他播放和体验问题优化
releaseDate: "2022-01-13T07:06:12.409Z"
silentUpdate: false
```

PackageVersion: `$result.version`
InstallerUrl:
```PowerShell
$url = "https://pc.ximalaya.com/ximalaya-pc-updater/api/v1/update/full/$($result.path)"
# "https://pc.ximalaya.com/ximalaya-pc-updater/api/v1/update/full/Ximalaya_2.4.0_1642057344.exe"
$response = Invoke-WebRequest $url -Method Head -Headers @{
platform = 'win32'
buildversion = '0'
version = '0.0.0'
uid = ''
}
$realurl = $response.BaseResponse.RequestMessage.RequestUri.AbsoluteUri
```
If this fails, use
```PowerShell
"https://s1.xmcdn.com/yx/ximalaya-pc-client/$($result.url)/download/win32-ia32/$($result.path)"
# https://s1.xmcdn.com/yx/ximalaya-pc-client/2.4.0/download/win32-ia32/Ximalaya_2.4.0_1642057344.exe
```
instead.
