### ISSUE TITLE
[New Package]: Hellofont.Hellofont

### ISSUE THREAD

**Issue by SpecterShell** [vedantmgoyal2009/vedantmgoyal2009#271]
### List the PackageIdentifier of the package to be added to automation

Hellofont.Hellofont

### Details about the application

https://hellofont.oss-cn-beijing.aliyuncs.com/Client/Release/latest.yml
```YAML
version: 3.0.2
files:
  - url: 字由 Setup 3.0.2.exe
    sha512: JV4IoX29GZcP1Lt0ZN0RNzRqltShn8PHlwrAGhitv3eTU/LFGW3IyQoO3Z8RzzM+vs5Z3jc5Gj7u/n5LwFl8dA==
    size: 86922815
path: 字由 Setup 3.0.2.exe
sha512: JV4IoX29GZcP1Lt0ZN0RNzRqltShn8PHlwrAGhitv3eTU/LFGW3IyQoO3Z8RzzM+vs5Z3jc5Gj7u/n5LwFl8dA==
releaseDate: '2021-12-24T10:38:59.991Z'
releaseName: '<b>此次我们更新了以下内容</b>'
releaseNotes: '1 增加了暗模式：<br/>&nbsp;&nbsp;&nbsp;- 可以在字由客户端右上角，点击按钮切换：<br/>2 增加了贴边隐藏的功能：<br/>&nbsp;&nbsp;&nbsp;- 在设置中选择「启用自动贴边隐藏」并且在字由为完成模式的情况下，靠近屏幕边缘即可自动隐藏<br/>3 系统优化：<br/>&nbsp;&nbsp;&nbsp;- 支持并优化了PS2022的一键应用功能<br/>&nbsp;&nbsp;&nbsp;- 支持了选择安装位置的功能<br/>&nbsp;&nbsp;&nbsp;- 提升了字体服务更新之后客户端的同步效率<br/>&nbsp;&nbsp;&nbsp;- 扩充了本地字体读取的服务范围，能读取到更多字体了<br/>4 问题修复：<br/>&nbsp;&nbsp;&nbsp;- 修复了某些情况下增删分组之后字体激活状态的同步问题<br/>&nbsp;&nbsp;&nbsp;- 修复了某些情况下家族字不能全部收藏的问题'
```
https://github.com/microsoft/winget-pkgs/pull/43402
